### ISSUE TITLE
ユーザーページに出てくる「リーダーをしているプロジェクト」一覧を、進行中/完了に分ける

### ISSUE THREAD

**Issue by coelacanth0715** [selelab/admin-api#10]
タイトルのまんまです。見やすさのために。優先度は低いです

**Comment by coelacanth0715** [comment]
![image](https://user-images.githubusercontent.com/62389508/77141851-a2c0d400-6ac1-11ea-9670-e8466cbc313d.png)

このページを、完了/非完了に分ける

**Comment by Tsutomu-Ikeda** [comment]
https://selelab.com/admin/projects/ で対応済み
![image](https://user-images.githubusercontent.com/40418321/77142000-1cf15880-6ac2-11ea-9be7-d59f21fc227f.png)

**Comment by Tsutomu-Ikeda** [comment]
https://selelab.com/admin/projects/ で対応済み
![image](https://user-images.githubusercontent.com/40418321/77142028-3f837180-6ac2-11ea-8a09-cb1302964569.png)
